###
### THIS PYTHON FILE WILL ACT AS A SERVER FOR THE FLASK APPLICATION THAT RUNS TIGERENGINE AND COMMUNICATES WITH CHESSBUDDY
### V1.0
### (c) INERTIA ROBOTICS
###

from flask import Flask, request, jsonify
